name: Robot Code CD
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build robot code
      run: docker build Robot -t frc4488:latest
    - name: Cleanup
      run: docker system prune -f

